### PR TITLE
Update Meteo runtime

### PR DESCRIPTION
**Pull request by ghost**
- Update Meteo runtime to 46
- Add webkitgtk-2

### CODE REVIEW

**Comment by ghost** [comment]
1.5 mb to 120mb. Not impressive!

resim

**Comment by ghost** [comment]
@bitseater, I updated the Meteo runtime from version 42 to 46.

However, WebKitGTK has caused an increase in the flatpak size, ballooning it from 1.5 MB to 120 MB!

I had to build WebKitGTK from scratch due to a dependency on libsoup 2.

It's a bit of a double-edged sword situation. Either using out-of-date runtime or using a bloated flatpak with up-to-date runtime.

**Comment by ghost** [comment]
@barthalion I updated the Meteo runtime from version 42 to 46.

However, WebKitGTK has caused an increase in the flatpak size, ballooning it from 1.5 MB to 120 MB!

**Comment by bitseater** [comment]
@yakushabb ...or you can rewrite all the code of Meteo with WebKitGTK and libsoup3.

**Comment by ghost** [comment]
Its beyond my knowledge. I'm familiar with PHP and other web-related technologies.

I should learn at least Python thoroughly.

**Pull request merged**
